disabled_rules:
  - cyclomatic_complexity
  - line_length
  - function_body_length
  - type_body_length
  - todo
  - type_name
  - identifier_name
  - multiple_closures_with_trailing_closure

included:
  - SGU_Schedule
  - SGU_ScheduleWidget
  
excluded:
  - Pods
